version: '3.8'

services:
  tags_api:
    build:
      context: .
      dockerfile: TagsAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - tags_db
      - tags_api_unit_tests
      - tags_api_integration_tests
  
  tags_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1434"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"

  tags_api_unit_tests:
    build:
      context: .
      dockerfile: TagsAPI.UnitTests/Dockerfile

  tags_api_integration_tests:
    build:
      context: .
      dockerfile: TagsAPI.IntegrationTests/Dockerfile